/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dispersion_probe.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(90b15d1c615ed89e1d6666be103ae8cf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <TFMv5/dispersion_probe.h>
// pydoc.h is automatically generated in the build directory
#include <dispersion_probe_pydoc.h>

void bind_dispersion_probe(py::module& m)
{

    using dispersion_probe    = ::gr::TFMv5::dispersion_probe;


    py::class_<dispersion_probe, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<dispersion_probe>>(m, "dispersion_probe", D(dispersion_probe))

        .def(py::init(&dispersion_probe::make),
           py::arg("constellation"),
           py::arg("length"),
           py::arg("length_init"),
           py::arg("th1"),
           py::arg("th2"),
           py::arg("th3"),
           py::arg("th4"),
           py::arg("th5"),
           py::arg("th6"),
           D(dispersion_probe,make)
        )
        



        ;




}








