/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(energy_scale.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7a1997f9bade734c5fb92c394dd110c6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <TFMv5/energy_scale.h>
// pydoc.h is automatically generated in the build directory
#include <energy_scale_pydoc.h>

void bind_energy_scale(py::module& m)
{

    using energy_scale    = ::gr::TFMv5::energy_scale;


    py::class_<energy_scale, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<energy_scale>>(m, "energy_scale", D(energy_scale))

        .def(py::init(&energy_scale::make),
           py::arg("eavg"),
           py::arg("length"),
           py::arg("init_scale"),
           D(energy_scale,make)
        )
        



        ;




}








