/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(per_probe.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6a0705eaffb01a7f54795d927b23fb8f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <TFMv5/per_probe.h>
// pydoc.h is automatically generated in the build directory
#include <per_probe_pydoc.h>

void bind_per_probe(py::module& m)
{

    using per_probe    = ::gr::TFMv5::per_probe;


    py::class_<per_probe, gr::block, gr::basic_block,
        std::shared_ptr<per_probe>>(m, "per_probe", D(per_probe))

        .def(py::init(&per_probe::make),
           py::arg("npackets"),
           D(per_probe,make)
        )
        



        ;




}








